AllCops:
  Exclude:
    - app/channels/**/*
    - app/mailers/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - Rakefile
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - vendor/**/*
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false
